display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  log:
    category:
      "io.quarkus.smallrye.jwt.runtime.auth.MpJwtValidator":
        level: "TRACE"

    console:
      json:
        false
  #        pretty-print: true
  #        date-format: "YYYY-MM-dd HH:mm:ss"
  #        exception-output-type: "detailed-and-formatted"
  datasource:
    "ebdb":
      db-kind:
        mysql
      reactive:
        url:
          mysql://localhost:3306/ebdb
        max-size:
          100
      username:
        root
      password:
        root
